// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApplication - メインのDIコンテナ
func InitializeApplication(ctx context.Context, config Config, logger *slog.Logger) (*Application, error) {
	// This will be generated by Wire
	panic("wire: not implemented")
}