// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gogym-api/internal/adapter/handler"
	"gogym-api/internal/adapter/repository/gym"
	"gogym-api/internal/adapter/repository/user"
	"gogym-api/internal/adapter/repository/workout"
	"gogym-api/internal/infra/security"
	"gogym-api/internal/infra/slack"
	"gogym-api/internal/usecase/contact"
	gym2 "gogym-api/internal/usecase/gym"
	"gogym-api/internal/usecase/session"
	user2 "gogym-api/internal/usecase/user"
	workout2 "gogym-api/internal/usecase/workout"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Initialize(db *gorm.DB, slackClient *slack.Client, jwtSecret string) *Handlers {
	userRepository := user.NewUserRepository(db)
	bcryptPasswordHasher := security.NewBcryptPasswordHasher()
	userUseCase := user2.NewUserInteractor(userRepository, bcryptPasswordHasher)
	userHandler := handler.NewUserHandler(userUseCase)
	sessionUseCase := session.NewSessionInteractor(userRepository, bcryptPasswordHasher, jwtSecret)
	sessionHandler := handler.NewSessionHandler(sessionUseCase)
	repository := gym.NewGymRepository(db)
	gymUseCase := gym2.NewGymInteractor(repository)
	gymHandler := handler.NewGymHandler(gymUseCase)
	workoutRepository := workout.NewWorkoutRepository(db)
	workoutUseCase := workout2.NewWorkoutInteractor(workoutRepository, repository)
	workoutHandler := handler.NewWorkoutHandler(workoutUseCase)
	slackGateway := provideSlackGateway(slackClient)
	contactUseCase := contact.NewContactInteractor(slackGateway)
	contactHandler := handler.NewContactHandler(contactUseCase)
	handlers := NewHandlers(userHandler, sessionHandler, gymHandler, workoutHandler, contactHandler)
	return handlers
}

// wire.go:

type Handlers struct {
	User    *handler.UserHandler
	Session *handler.SessionHandler
	Gym     *handler.GymHandler
	Workout *handler.WorkoutHandler
	Contact *handler.ContactHandler
}

func NewHandlers(user3 *handler.UserHandler, session2 *handler.SessionHandler, gym3 *handler.GymHandler, workout3 *handler.WorkoutHandler, contact2 *handler.ContactHandler,
) *Handlers {
	return &Handlers{
		User:    user3,
		Session: session2,
		Gym:     gym3,
		Workout: workout3,
		Contact: contact2,
	}
}

var repositorySet = wire.NewSet(user.NewUserRepository, gym.NewGymRepository, workout.NewWorkoutRepository, wire.Bind(new(user2.Repository), new(*user.UserRepository)), wire.Bind(new(session.UserRepository), new(*user.UserRepository)))

var securitySet = wire.NewSet(security.NewBcryptPasswordHasher, wire.Bind(new(user2.PasswordHasher), new(*security.BcryptPasswordHasher)), wire.Bind(new(session.PasswordHasher), new(*security.BcryptPasswordHasher)))

var usecaseSet = wire.NewSet(user2.NewUserInteractor, session.NewSessionInteractor, gym2.NewGymInteractor, workout2.NewWorkoutInteractor, contact.NewContactInteractor)

var handlerSet = wire.NewSet(handler.NewUserHandler, handler.NewSessionHandler, handler.NewGymHandler, handler.NewWorkoutHandler, handler.NewContactHandler, NewHandlers)

// provideSlackGateway converts *slack.Client to contactuc.SlackGateway interface
func provideSlackGateway(client *slack.Client) contact.SlackGateway {
	return client
}

var gatewaySet = wire.NewSet(
	provideSlackGateway,
)
