version: "3"

# ─────────────────────────────────────────────────────────────
# Minimal tasks: db / api / web / seed だけに絞った構成
# 初回は「task setup」で DB 起動＆シード投入まで完了
# 日常は「task db:up」「task api」「task web」を並行実行
# ─────────────────────────────────────────────────────────────

vars:
  DOCKER_COMPOSE_FILE: ./infra/docker-compose.yml
  API_DIR: ./apps/api
  WEB_DIR: ./apps/web
  SEED_FILE: ./apps/api/internal/infra/db/seeds/seed.sql
  AIR_VERSION: v1.61.1

tasks:
  # ========= One-shot =========
  setup:
    desc: 初回セットアップ（DB起動→シード投入）
    cmds:
      - task: db:up
      - task: db:wait
      - task: db:seed
      - echo "✅ DB起動＆シード投入完了"

  # ========= DB only (Docker) =========
  db:up:
    desc: データベース(MySQL)をDockerで起動
    cmds:
      - echo "🚀 MySQLを起動中..."
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up -d mysql
      - echo "✅ MySQL起動完了（ポート 3307→3306@container）"

  db:down:
    desc: データベース(MySQL)を停止
    cmds:
      - echo "🛑 MySQLを停止中..."
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down
      - echo "✅ 停止完了"

  db:logs:
    desc: MySQLログをフォロー表示
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} logs -f mysql

  db:wait:
    desc: MySQLが受け付け可能になるまで待機
    silent: true
    cmds:
      - |
        echo "⏳ MySQLの起動待ち..."
        for i in {1..60}; do
          docker compose -f {{.DOCKER_COMPOSE_FILE}} exec -T mysql \
            mysqladmin ping -h 127.0.0.1 -u root -ppassword --silent && break
          sleep 1
        done
        echo "✅ MySQL is ready"

  db:seed:
    desc: シードデータを投入（Docker上のMySQLへ）
    cmds:
      - |
        echo "🌱 シード投入: {{.SEED_FILE}}"
        test -f {{.SEED_FILE}} || (echo "❌ SEED_FILEが見つかりません: {{.SEED_FILE}}" && exit 1)
        # -T を付けてstdinパイプを正しく渡す
        docker compose -f {{.DOCKER_COMPOSE_FILE}} exec -T mysql \
          mysql -u gogym -ppassword -D gogym < {{.SEED_FILE}}
        echo "✅ シード投入完了"

  # ========= API (local with Air) =========
  api:
    desc: APIをローカル起動（Airでホットリロード）
    dir: "{{.API_DIR}}"
    deps: [api:air-setup]
    cmds:
      - echo "🔧 API起動 (air)"
      - air

  api:air-setup:
    desc: Airを特定バージョンでインストール（idempotent）
    internal: true
    cmds:
      - go install github.com/air-verse/air@{{.AIR_VERSION}}

  # ========= Web (local) =========
  web:
    desc: Webをローカル起動（npm run dev）
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "⚡ Web起動 (npm run dev)"
      - npm run dev
