default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: GoGym_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: GoGym_test
  host: db
  username: postgres
  password: password

# renderデプロイ時の設定
production:
  <<: *default
  database: gogymdb
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
