# Prometheus 設定ファイル
# GoGym アプリケーション用メトリクス収集設定

global:
  scrape_interval: 15s # メトリクス収集間隔
  evaluation_interval: 15s # ルール評価間隔
  external_labels:
    monitor: 'gogym-monitor'

rule_files:
  # アラートルールファイルがあればここに追加
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus 自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MySQL データベース監視
  # MySQL Exporterを使用する場合の設定（オプション）
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']

  # Redis 監視
  # Redis Exporterを使用する場合の設定（オプション）
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Go API サーバー監視
  # APIサーバーがPrometheusメトリクスを公開している場合
  - job_name: 'gogym-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    # APIサーバーが起動していない場合はエラーになるが問題なし

  # Node Exporter（システムメトリクス）
  # システムリソース監視用（オプション）
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']