version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gogym-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gogym
      MYSQL_USER: gogym
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+09:00
    networks:
      - gogym-network

  redis:
    image: redis:7-alpine
    container_name: gogym-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - gogym-network

  minio:
    image: minio/minio:latest
    container_name: gogym-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - gogym-network

  minio-init:
    image: minio/mc:latest
    container_name: gogym-minio-init
    depends_on:
      - minio
    volumes:
      - ./minio-init.sh:/minio-init.sh
    entrypoint: /bin/sh
    command: -c "chmod +x /minio-init.sh && /minio-init.sh"
    networks:
      - gogym-network

  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: gogym-imgproxy
    ports:
      - "8081:8080"
    environment:
      IMGPROXY_BIND: "0.0.0.0:8080"
      IMGPROXY_USE_S3: "true"
      IMGPROXY_S3_ENDPOINT: "http://minio:9000"
      IMGPROXY_S3_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin123"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /var/lib/imgproxy
      IMGPROXY_ALLOW_ORIGIN: "*"
    depends_on:
      - minio
    networks:
      - gogym-network

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    container_name: gogym-api
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=gogym
      - DB_USER=gogym
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=gogym-photos
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin123
      - S3_REGION=us-east-1
      - S3_PUBLIC_URL=http://localhost:9000/gogym-photos
      - IMGPROXY_BASE_URL=http://imgproxy:8080
      - LOG_LEVEL=debug
    depends_on:
      - mysql
      - redis
      - minio
    volumes:
      - ../../apps/api:/app
    networks:
      - gogym-network
    restart: unless-stopped

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    container_name: gogym-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_IMGPROXY_URL=http://localhost:8081
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - gogym-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  gogym-network:
    driver: bridge