// Code generated by MockGen. DO NOT EDIT.
// Source: workout_output.go

// Package workout is a generated GoMock package.
package workout

import (
	context "context"
	dw "gogym-api/internal/domain/entities/workout"
	reflect "reflect"
	"time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountUserWorkoutParts mocks base method.
func (m *MockRepository) CountUserWorkoutParts(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserWorkoutParts", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserWorkoutParts indicates an expected call of CountUserWorkoutParts.
func (mr *MockRepositoryMockRecorder) CountUserWorkoutParts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserWorkoutParts", reflect.TypeOf((*MockRepository)(nil).CountUserWorkoutParts), ctx, userID)
}

// CreateWorkoutParts mocks base method.
func (m *MockRepository) CreateWorkoutParts(ctx context.Context, userID string, parts []dw.WorkoutPart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkoutParts", ctx, userID, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkoutParts indicates an expected call of CreateWorkoutParts.
func (mr *MockRepositoryMockRecorder) CreateWorkoutParts(ctx, userID, parts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkoutParts", reflect.TypeOf((*MockRepository)(nil).CreateWorkoutParts), ctx, userID, parts)
}

// CreateWorkoutRecord mocks base method.
func (m *MockRepository) CreateWorkoutRecord(ctx context.Context, workout dw.WorkoutRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkoutRecord", ctx, workout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkoutRecord indicates an expected call of CreateWorkoutRecord.
func (mr *MockRepositoryMockRecorder) CreateWorkoutRecord(ctx, workout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkoutRecord", reflect.TypeOf((*MockRepository)(nil).CreateWorkoutRecord), ctx, workout)
}

// DeleteWorkoutExercise mocks base method.
func (m *MockRepository) DeleteWorkoutExercise(ctx context.Context, userID string, exerciseID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkoutExercise", ctx, userID, exerciseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkoutExercise indicates an expected call of DeleteWorkoutExercise.
func (mr *MockRepositoryMockRecorder) DeleteWorkoutExercise(ctx, userID, exerciseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkoutExercise", reflect.TypeOf((*MockRepository)(nil).DeleteWorkoutExercise), ctx, userID, exerciseID)
}

// GetLastWorkoutRecord mocks base method.
func (m *MockRepository) GetLastWorkoutRecord(ctx context.Context, userID string, exerciseID int64) (dw.WorkoutRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastWorkoutRecord", ctx, userID, exerciseID)
	ret0, _ := ret[0].(dw.WorkoutRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastWorkoutRecord indicates an expected call of GetLastWorkoutRecord.
func (mr *MockRepositoryMockRecorder) GetLastWorkoutRecord(ctx, userID, exerciseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastWorkoutRecord", reflect.TypeOf((*MockRepository)(nil).GetLastWorkoutRecord), ctx, userID, exerciseID)
}

// GetRecordsByDate mocks base method.
func (m *MockRepository) GetRecordsByDate(ctx context.Context, userID string, date time.Time) (dw.WorkoutRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByDate", ctx, userID, date)
	ret0, _ := ret[0].(dw.WorkoutRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByDate indicates an expected call of GetRecordsByDate.
func (mr *MockRepositoryMockRecorder) GetRecordsByDate(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByDate", reflect.TypeOf((*MockRepository)(nil).GetRecordsByDate), ctx, userID, date)
}

// GetWorkoutParts mocks base method.
func (m *MockRepository) GetWorkoutParts(ctx context.Context, userID string) ([]dw.WorkoutPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkoutParts", ctx, userID)
	ret0, _ := ret[0].([]dw.WorkoutPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkoutParts indicates an expected call of GetWorkoutParts.
func (mr *MockRepositoryMockRecorder) GetWorkoutParts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkoutParts", reflect.TypeOf((*MockRepository)(nil).GetWorkoutParts), ctx, userID)
}

// UpsertWorkoutExercises mocks base method.
func (m *MockRepository) UpsertWorkoutExercises(ctx context.Context, userID string, exercises []dw.WorkoutExerciseRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorkoutExercises", ctx, userID, exercises)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWorkoutExercises indicates an expected call of UpsertWorkoutExercises.
func (mr *MockRepositoryMockRecorder) UpsertWorkoutExercises(ctx, userID, exercises interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorkoutExercises", reflect.TypeOf((*MockRepository)(nil).UpsertWorkoutExercises), ctx, userID, exercises)
}

// UpsertWorkoutRecord mocks base method.
func (m *MockRepository) UpsertWorkoutRecord(ctx context.Context, workout dw.WorkoutRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorkoutRecord", ctx, workout)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWorkoutRecord indicates an expected call of UpsertWorkoutRecord.
func (mr *MockRepositoryMockRecorder) UpsertWorkoutRecord(ctx, workout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorkoutRecord", reflect.TypeOf((*MockRepository)(nil).UpsertWorkoutRecord), ctx, workout)
}
