# Grafana データソース自動プロビジョニング設定
# 起動時に自動的にデータソースを設定

apiVersion: 1

datasources:
  # Prometheus データソース（メトリクス監視用）
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s
    version: 1

  # MySQL データソース（データベース監視・分析用）
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: gogym
    user: gogym
    secureJsonData:
      password: password
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    version: 1